### ISSUE TITLE
[ML] Upgrade compilers so that we can use C++17 in the 8.x timeframe

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#1015]
Currently in our codebase we are able to use C++11 in the 6.x branches and C++14 in the 7.x branches.

It would be good if we can use C++17 in the 8.x branches (once they are eventually created).  Enabling this will require compiler upgrades on our release build environments for all platforms:

- [x] macOS - requires Xcode 10 or above - #867
- [x] Linux - requires gcc 7 (partial) or 9 (complete) - #1170
- [ ] Windows - requires Visual Studio 2019 - #1352

When the compilers are upgraded we will also take the opportunity to upgrade libxml2 from version 2.9.4 to version 2.9.7 with minimal extra effort.

**Comment by droberts195** [comment]
#834 had to be backed out as the release manager VM had some components missing.  #1352 will be the replacement once the release manager VM is updated.
