### ISSUE TITLE
[ML] [PyTorch] 3rd Party Models Miscellaneous

### ISSUE THREAD

**Issue by davidkyle** [elastic/ml-cpp#1703]
## Meta tracking for 3rd Party Model issues

- [x] Add libtorch to `dependency_report.sh` #1816
- [x] Add sentiment analysis example for the `evaluate.py` test script
- [x] Decide and document minimum acceptable CPU instruction requirement, and ensure that it is met - Resolved by using Intel MKL #2008
- [x] Investigate LibTorch multi-threading #1815

**Comment by droberts195** [comment]
> Decide and document minimum acceptable CPU instruction requirement, and ensure that it is met

To elaborate on this, currently we require a minimum of SSE4.2, documented [here](https://www.elastic.co/guide/en/machine-learning/7.10/ml-limitations.html#ml-limitations-sse).

FBGEMM requires at minimum AVX2.  It can take advantage of AVX512 if that is available.  There _might_ be an option to use Caffe2 instead of FBGEMM and avoid this requirement (presumably at a cost of lower performance on hardware that _does_ have those instructions).

In versions 5.4 to 6.0 we required SSE3 vector extensions.  These are really old and we never had a report of anyone running into a problem through not having them.

In version 6.1 we advanced this to requiring SSE4.2 vector extensions.  This caused a small number of users to be unable to use ML due to running on old hardware.  Evidence from Discuss:

- https://discuss.elastic.co/t/elasticsearch-7-1-1-failed-to-create-native-process-factories-for-machine-learning/184006/5
- https://discuss.elastic.co/t/ml-job-failed-autodetect-process-stopped-unexpectedly-fatal-error/137867/2
- https://discuss.elastic.co/t/failed-to-start-machine-learning-on-elasticsearch-7-0-0/178216/8

If we were to advance the minimum requirement to AVX2 I suspect we would get a lot more problem reports.  AVX2 was added to Intel CPUs in Q2 2013 and AMD in Q2 2015 - see https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX2.  But these dates are the initial release dates.  Hardware containing previous generation CPUs continues to be sold for a couple of years after newer hardware is released.  So it's likely that some people would run into problems on machines they bought brand new as recently as spring 2017.

Therefore I don't think it would be acceptable to increase the minimum CPU requirement for the whole ML codebase.  What we _could_ do instead is to say that the minimum requirement for using the new PyTorch inference feature is AVX2, and check for this as early as possible in the lifecycle of each node, so that we can provide clear error messages to users who don't have AVX2 instructions available before they use the PyTorch functionality.  (This will also create a testing headache, as most public clouds contain very modern hardware, so we'll need to hunt down old hardware to test these error checks.)

**Comment by droberts195** [comment]
#1816 covers the dependency report
