### ISSUE TITLE
[ML] Hyperparameter optimization logging

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1713]
We have a hypothesis that line search for hyperparameter (`coarse_parameter_tuning`) phase is already doing such a good job, that the identified feasibility interval does not contain a solution that could improve the performance further (module random variation).

To investigate this hypothesis, we need to look at the logs of hyperparameter optimization path for some real-world scenarios.

- [ ] Is additional logging required?
- [ ] Can I run the jobs in the cloud myself and look at the logs?
- [ ] Summarize results in a google sheet.
