### ISSUE TITLE
[ML] Experiment tracking framework problems

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#2014]
- [x]  job files from `job_submitter` aren't getting removed even for successful runs
- [x] simple failure which doesn't seem to propagate to the ES cluster is setting the memory limit too low (fixed in #2016)
- [x] some of the parameters the incremental training parameters, like test train gap, are not yet set from `update` (fixed in #2015)
- [x] Add a force option to always select incremental train result (useful anyway and there appears to be an issue with estimating cross-validation error for the original model) (addressed in #2017)
