### ISSUE TITLE
[ML] Per partition normalisation tracking maximum scores for distinct over field and all influencer fields

### ISSUE THREAD

**Issue by tveasey** [elastic/ml-cpp#210]
There were a couple of inadvertent changes introduced by #182. These have caused large slow downs, and also many more high severity anomalies, in some of our regression suite data sets. The changes we want to "revert" are:
- [x] We now have one maximum score per distinct over field value for population analysis
- [ ] We now have one maximum score per distinct value of *all* influencer fields
- [ ] We don't remove maximum scores after removing the corresponding models

Items 1 and 2, in the case that the influencer is not one of the detector partitioning fields, was not intended in the original plan for this work. The current behaviour is not really appropriate since the presence of particular values of these fields in the data set are often transitory.

Item 3 means we gradually "leak" maximum scores over time and could eventually cause us problems.

This hasn't been released so marking as a non-issue.
