### ISSUE TITLE
[ML] Windows build warnings

### ISSUE THREAD

**Issue by edsavage** [elastic/ml-cpp#2653]
Examination of the Windows build logs shows a number of instances of the following warnings.

- [x] C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\bin\pytorch_inference\CCommandParser.cc(26,68): warning C4273: std::ostream& operator<<(std::ostream& os, const json::value& doc) { [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\bin\pytorch_inference\Mlpytorch_inference.vcxproj] - #2654
- [x]     12>C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\lib\model\CTokenListDataCategorizerBase.cc(429,1): warning C4573: the usage of 'ml::model::CTokenListDataCategorizerBase::acceptPersistInserter' requires the compiler to capture 'this' but the current default capture mode does not allow it [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\lib\model\MlModel.vcxproj] - #2655
- [x]     13>zlib.lib(deflate.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with 'zlib.lib(deflate.obj)' or at 'C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\lib\core\RelWithDebInfo\zlib.pdb'; linking object as if no debug info [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\lib\core\MlCore.vcxproj] - #2659 
- [x]     13>LINK : warning LNK4217: symbol '??0shared_resource@detail@json@boost@@QEAA@XZ (public: __cdecl boost::json::detail::shared_resource::shared_resource(void))' defined in 'CJsonLogLayout.obj' is imported by 'CBoostJsonConcurrentLineWriter.obj' in function '"class std::shared_ptr<class ml::core::CBoostJsonPoolAllocator> __cdecl std::make_shared<class ml::core::CBoostJsonPoolAllocator>(void)" (??$make_shared@VCBoostJsonPoolAllocator@core@ml@@$$V@std@@YA?AV?$shared_ptr@VCBoostJsonPoolAllocator@core@ml@@@0@XZ)' [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\lib\core\MlCore.vcxproj] - #2656

It would be good to address these at some point as they could potentially obscure more severe issues in the future.

**Comment by edsavage** [comment]
Closing as all sub-issues are now complete.
