### ISSUE TITLE
[ML] Add information about samples per node to the tree

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#850]
I propose to extend the node definition by adding information about the number of training samples that passed through the node. This information provide one of the simpler feature importance indicators (see[ xgboost cover](https://xgboost.readthedocs.io/en/latest/R-package/discoverYourData.html#measure-feature-importance)). It also helps to test and  prevent degenerated trees such as those described in #849 .

#### Sub-Tasks
- [x] Update schema definition
- [x] Update `Node` logic
- [x] Update inference model code
- [x] Update persist/restore schema version
- [x] Add enhancement note
